repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        name: Check YAML
      - id: check-json
        name: Check JSON
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
      - id: terraform-docs-go
        alias: azuredevops
        name: Azure DevOps
        args:
          [
            "markdown",
            "./infrastructure/azuredevops",
            "--output-mode",
            "replace",
            "--output-file",
            "README.md",
          ]
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.1.27
    hooks:
      - id: checkov
        name: Static Code Analysis
        args:
          [
            "--quiet",
            "--compact",
            "--soft-fail",
            "--download-external-modules",
            "True",
            "--directory",
            ".",
          ]
